In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Toyota Etios 2014 Dataset (motion)

In [31]:
df__etios_1=pd.read_csv("Toyota Etios 2014 1.5/live3.csv")

df__etios_1.head()

,ENGINE_RUN_TINE (),ENGINE_RPM (),VEHICLE_SPEED (),THROTTLE (),ENGINE_LOAD (),COOLANT_TEMPERATURE (),LONG_TERM_FUEL_TRIM_BANK_1 (),SHORT_TERM_FUEL_TRIM_BANK_1 (),INTAKE_MANIFOLD_PRESSURE (),FUEL_TANK (),...,INTAKE_AIR_TEMP (),TIMING_ADVANCE (),CATALYST_TEMPERATURE_BANK1_SENSOR1 (),CATALYST_TEMPERATURE_BANK1_SENSOR2 (),CONTROL_MODULE_VOLTAGE (),COMMANDED_EVAPORATIVE_PURGE (),TIME_RUN_WITH_MIL_ON (),TIME_SINCE_TROUBLE_CODES_CLEARED (),DISTANCE_TRAVELED_WITH_MIL_ON (),WARM_UPS_SINCE_CODES_CLEARED ()
0.0,0.0,0.0,17.647058,0.0,25.0,-4.6875,0.0,101.0,32.156864,49.803921,...,5.0,442.600006,301.399994,12.363,0.0,0.0,7902.0,0.0,255.0,NaN
0.0,0.0,0.0,17.647058,0.0,25.0,-4.6875,0.0,101.0,32.156864,49.803921,...,5.0,442.600006,301.399994,12.363,0.0,0.0,7902.0,0.0,255.0,NaN
0.0,0.0,0.0,17.647058,0.0,25.0,-4.6875,0.0,101.0,32.156864,49.803921,...,5.0,442.600006,301.399994,12.363,0.0,0.0,7902.0,0.0,255.0,NaN
0.0,0.0,0.0,17.647058,0.0,25.0,-4.6875,0.0,101.0,32.156864,49.803921,...,5.0,442.600006,301.399994,12.363,0.0,0.0,7902.0,0.0,255.0,NaN
0.0,0.0,0.0,19.607843,0.0,25.0,-4.6875,0.0,101.0,32.156864,49.803921,...,5.0,442.600006,301.399994,12.363,0.0,0.0,7902.0,0.0,255.0,NaN

In [4]:
df_test= pd.read_csv("exp2_19drivers_1car_1route.csv")
df_test.head()

,TIME,LATITUDE,LONGITUDE,ALTITUDE,VEHICLE_ID,BAROMETRIC_PRESSURE,ENGINE_COOLANT_TEMP,FUEL_LEVEL,ENGINE_LOAD,AMBIENT_AIR_TEMP,...,FUEL_PRESSURE,SPEED,Short Term Fuel Trim Bank 2,Short Term Fuel Trim Bank 1,ENGINE_RUNTIME,THROTTLE_POS,DTC_NUMBER,TROUBLE_CODES,TIMING_ADVANCE,EQUIV_RATIO
0,"1,51336E+12",-58.321.307,-3.520.429.461,46.0,s11,100kPa,82C,"74,50%","79,20%",28C,...,NaN,48km/h,NaN,"-1,60%",00:03:02,"34,90%",MIL is OFF0 codes,NaN,"66,70%","1,00%"
1,"1,51336E+12",-58.323.103,-3.520.380.397,52.0,s11,100kPa,83C,"74,10%","78,40%",28C,...,NaN,60km/h,NaN,"-4,70%",00:03:08,"36,10%",MIL is OFF0 codes,NaN,"68,20%","1,00%"
2,"1,51336E+12",-583.251.443,-3.520.323.709,49.0,s11,100kPa,83C,"73,70%","42,00%",28C,...,NaN,64km/h,NaN,"-10,20%",00:03:12,"32,20%",MIL is OFF0 codes,NaN,"75,70%","1,00%"
3,"1,51336E+12",-58.328.462,-3.520.269.621,45.0,s11,100kPa,82C,"73,70%","37,30%",28C,...,NaN,65km/h,NaN,"0,00%",00:03:16,"32,50%",MIL is OFF0 codes,NaN,"75,30%","1,00%"
4,"1,51336E+12",-583.324.508,-3.520.219.432,44.0,s11,100kPa,82C,"73,30%","76,10%",28C,...,NaN,67km/h,NaN,"3,10%",00:03:20,"33,30%",MIL is OFF0 codes,NaN,"66,30%","1,00%"

In [5]:
df_test_1= pd.read_csv("exp1_14drivers_14cars_dailyRoutes.csv")
df_test_1.head()

C:\Users\Ahmed Medhat\AppData\Local\Temp\ipykernel_3712\3093985735.py:1: DtypeWarning: Columns (1,2,4,5,6,9,10,14,15,16,20,21,22,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df_test_1= pd.read_csv("exp1_14drivers_14cars_dailyRoutes.csv")

,TIMESTAMP,MARK,MODEL,CAR_YEAR,ENGINE_POWER,AUTOMATIC,VEHICLE_ID,BAROMETRIC_PRESSURE(KPA),ENGINE_COOLANT_TEMP,FUEL_LEVEL,...,THROTTLE_POS,DTC_NUMBER,TROUBLE_CODES,TIMING_ADVANCE,EQUIV_RATIO,MIN,HOURS,DAYS_OF_WEEK,MONTHS,YEAR
0,1.502903e+12,chevrolet,agile,2011.0,"1,4",n,car1,100.0,80.0,"48,60%",...,25%,MIL is OFF0 codes,NaN,"56,9%","1,0%",13.0,16.0,2.0,8.0,2017.0
1,1.502903e+12,chevrolet,agile,2011.0,"1,4",n,car1,100.0,80.0,"48,60%",...,25%,MIL is OFF0 codes,NaN,"56,5%","1,0%",13.0,16.0,2.0,8.0,2017.0
2,1.502903e+12,chevrolet,agile,2011.0,"1,4",n,car1,100.0,80.0,"48,60%",...,25%,MIL is OFF0 codes,NaN,"57,3%","1,0%",13.0,16.0,2.0,8.0,2017.0
3,1.502903e+12,chevrolet,agile,2011.0,"1,4",n,car1,100.0,80.0,"48,60%",...,25%,MIL is OFF0 codes,NaN,"56,5%","1,0%",13.0,16.0,2.0,8.0,2017.0
4,1.502903e+12,chevrolet,agile,2011.0,"1,4",n,car1,100.0,80.0,"48,60%",...,25%,MIL is OFF0 codes,NaN,"56,9%","1,0%",13.0,16.0,2.0,8.0,2017.0

In [27]:
# df_test_1['MARK']['chevrolet'].unique()
chev_data=df_test_1[df_test_1['MARK'] == 'chevrolet']

In [29]:
chev_data['CAR_YEAR'].unique()

array([2011.])