In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df =pd.read_csv('live28.csv')
df.head()

,ENGINE_RUN_TINE (),ENGINE_RPM (),VEHICLE_SPEED (),THROTTLE (),ENGINE_LOAD (),COOLANT_TEMPERATURE (),LONG_TERM_FUEL_TRIM_BANK_1 (),SHORT_TERM_FUEL_TRIM_BANK_1 (),INTAKE_MANIFOLD_PRESSURE (),FUEL_TANK (),...,INTAKE_AIR_TEMP (),TIMING_ADVANCE (),CATALYST_TEMPERATURE_BANK1_SENSOR1 (),CATALYST_TEMPERATURE_BANK1_SENSOR2 (),CONTROL_MODULE_VOLTAGE (),COMMANDED_EVAPORATIVE_PURGE (),TIME_RUN_WITH_MIL_ON (),TIME_SINCE_TROUBLE_CODES_CLEARED (),DISTANCE_TRAVELED_WITH_MIL_ON (),WARM_UPS_SINCE_CODES_CLEARED ()
0.0,0.0,0.0,17.647058,0.000000,89.0,-5.46875,0.0,101.0,22.745098,49.411766,...,5.0,477.299988,359.700012,12.128,0.0,0.0,8945.0,0.0,255.0,NaN
0.0,0.0,0.0,17.647058,0.000000,89.0,-5.46875,0.0,101.0,22.745098,49.411766,...,5.0,477.299988,359.700012,12.128,0.0,0.0,8945.0,0.0,255.0,NaN
0.0,0.0,0.0,17.647058,0.000000,89.0,-5.46875,0.0,101.0,22.745098,49.411766,...,5.0,477.299988,359.700012,12.128,0.0,0.0,8945.0,0.0,255.0,NaN
0.0,0.0,0.0,17.647058,0.000000,89.0,-5.46875,0.0,101.0,22.745098,49.411766,...,5.0,477.299988,359.700012,9.218,0.0,0.0,8945.0,0.0,255.0,NaN
0.0,0.0,0.0,17.647058,41.176472,89.0,-5.46875,0.0,101.0,22.745098,49.411766,...,5.0,477.299988,359.700012,9.218,0.0,0.0,8945.0,0.0,255.0,NaN